export const languages: { [key: string]: string } = {
  "Árabe Clássico": "ar",
  Alemão: "de",
  Búlgaro: "bg",
  Chinês: "zh",
  Croata: "hr",
  Coreano: "ko",
  Dinamarquês: "da",
  Eslovaco: "sk",
  Espanhol: "es",
  Filipino: "fil",
  Finlandês: "fi",
  Francês: "fr",
  Grego: "el",
  Holandês: "nl",
  Húngaro: "hu",
  Hindi: "hi",
  Indonésio: "id",
  Inglês: "en",
  Italiano: "it",
  Japonês: "ja",
  Malaio: "ms",
  Norueguês: "no",
  Polonês: "pl",
  "Português de Portugal": "pt",
  "Português Brasileiro": "pt-BR",
  Romeno: "ro",
  Russo: "ru",
  Sueco: "sv",
  Tâmil: "ta",
  Tcheco: "cs",
  Turco: "tr",
  Ucraniano: "uk",
  Vietnamita: "vi",
};

export const languagesCodes = Object.keys(languages).map(
  (key) => languages[key],
);

export const languageNames = Object.keys(languages);
